import 'dart:convert';
import 'package:flutter/services.dart';
import 'package:safemed/models/medication.dart';

/// Service that loads medications from the Infarmed-scraped JSON asset.
///
/// The JSON is generated by the 4-step pipeline in:
///   drug_info_webscraping/  (run via webscraping_tools.bat -> option 1)
///     Step 1: acquire_drugs/dci_scrapper.py      -> outputs/dcis_infomed.json
///     Step 2: acquire_drugs/table_scrapper.py    -> outputs/medicamentos_infomed.json
///     Step 3: acquire_drugs/informative_bill_document_scrapper.py -> outputs/informative_bill_per_dci.json
///     Step 4: acquire_drugs/flutter_exporter.py  -> assets/medications_infarmed.json  (this file)
///
/// Requires GEMINI_API_KEY in drug_info_webscraping/acquire_drugs/.env for Step 3.
///
/// Usage:
///   final service = InfarmedMedicationService();
///   await service.init();
///   final results = service.search('paracetamol');
class InfarmedMedicationService {
  static const _assetPath = 'assets/medications_infarmed.json';

  List<Medication> _medications = [];
  List<_InfarmedEntry> _entries = [];
  bool _initialized = false;

  bool get isInitialized => _initialized;
  int get count => _medications.length;

  /// Load and parse the JSON asset. Call once at app startup.
  Future<void> init() async {
    if (_initialized) return;
    try {
      final jsonStr = await rootBundle.loadString(_assetPath);
      final list = jsonDecode(jsonStr) as List<dynamic>;
      _entries = list.map((e) => _InfarmedEntry.fromJson(e as Map<String, dynamic>)).toList();
      _medications = _entries.map((e) => e.toMedication()).toList();
      _initialized = true;
    } catch (e) {
      // Asset not yet generated (scraper hasn't run) — silently skip.
      _initialized = true;
      _medications = [];
      _entries = [];
    }
  }

  /// Returns all medications.
  List<Medication> get all => List.unmodifiable(_medications);

  /// Search by commercial name or active substance (case-insensitive).
  List<Medication> search(String query) {
    final q = _normalize(query);
    if (q.isEmpty) return const [];
    return _medications.where((m) {
      return _normalize(m.nomeComercial).contains(q) ||
          _normalize(m.substanciaAtiva).contains(q);
    }).toList();
  }

  /// Lookup by CNPEM code (exact match).
  Medication? findByCnpem(String cnpem) {
    final clean = cnpem.replaceAll(RegExp(r'\D'), '');
    try {
      return _medications.firstWhere(
        (m) => m.cnp.replaceAll(RegExp(r'\D'), '') == clean,
      );
    } catch (_) {
      return null;
    }
  }

  /// Lookup by medication ID.
  Medication? findById(String id) {
    try {
      return _medications.firstWhere((m) => m.id == id);
    } catch (_) {
      return null;
    }
  }

  /// Get the extended entry (includes PDF-extracted fields like therapeuticIndications,
  /// warnings, adverseReactions, pregnancyWarning, etc.) for a given Medication ID.
  _InfarmedEntry? getEntryById(String id) {
    try {
      return _entries.firstWhere((e) => e.id == id);
    } catch (_) {
      return null;
    }
  }

  static String _normalize(String input) {
    return input
        .toLowerCase()
        .replaceAll(RegExp(r'[àáâãä]'), 'a')
        .replaceAll(RegExp(r'[èéêë]'), 'e')
        .replaceAll(RegExp(r'[ìíîï]'), 'i')
        .replaceAll(RegExp(r'[òóôõö]'), 'o')
        .replaceAll(RegExp(r'[ùúûü]'), 'u')
        .replaceAll('ç', 'c')
        .replaceAll(RegExp(r'[^a-z0-9 ]'), ' ')
        .trim();
  }
}

/// Extended data class that holds all fields from the Infarmed JSON,
/// including PDF-extracted clinical information not in the base Medication model.
class _InfarmedEntry {
  final String id;
  final String cnp;
  final String nomeComercial;
  final String formaFarmaceutica;
  final String substanciaAtiva;
  final String dosagem;
  final String riscoGravidezStr;
  final int? idadeMinima;
  final bool sujeitoReceitaMedica;
  final List<String> contraindicacoes;
  final List<String> efeitosSecundariosComuns;
  // Extended / Infarmed-specific
  final String titularAIM;
  final String aimStatus;
  final double? pricePVP;
  final String isGeneric;
  final String therapeuticIndications;
  final String warnings;
  final String adverseReactions;
  final String howToStore;
  final String pregnancyWarning;
  final String fiUrl;
  final String rcmUrl;

  const _InfarmedEntry({
    required this.id,
    required this.cnp,
    required this.nomeComercial,
    required this.formaFarmaceutica,
    required this.substanciaAtiva,
    required this.dosagem,
    required this.riscoGravidezStr,
    this.idadeMinima,
    required this.sujeitoReceitaMedica,
    required this.contraindicacoes,
    required this.efeitosSecundariosComuns,
    this.titularAIM = '',
    this.aimStatus = '',
    this.pricePVP,
    this.isGeneric = '',
    this.therapeuticIndications = '',
    this.warnings = '',
    this.adverseReactions = '',
    this.howToStore = '',
    this.pregnancyWarning = '',
    this.fiUrl = '',
    this.rcmUrl = '',
  });

  factory _InfarmedEntry.fromJson(Map<String, dynamic> j) {
    return _InfarmedEntry(
      id: j['id'] as String? ?? '',
      cnp: j['cnp'] as String? ?? '',
      nomeComercial: j['nomeComercial'] as String? ?? '',
      formaFarmaceutica: j['formaFarmaceutica'] as String? ?? '',
      substanciaAtiva: j['substanciaAtiva'] as String? ?? '',
      dosagem: j['dosagem'] as String? ?? '',
      riscoGravidezStr: j['riscoGravidez'] as String? ?? 'B',
      idadeMinima: j['idadeMinima'] as int?,
      sujeitoReceitaMedica: j['sujeitoReceitaMedica'] as bool? ?? false,
      contraindicacoes: List<String>.from(j['contraindicacoes'] as List? ?? []),
      efeitosSecundariosComuns:
          List<String>.from(j['efeitosSecundariosComuns'] as List? ?? []),
      titularAIM: j['titularAIM'] as String? ?? '',
      aimStatus: j['aimStatus'] as String? ?? '',
      pricePVP: (j['pricePVP'] as num?)?.toDouble(),
      isGeneric: j['isGeneric'] as String? ?? '',
      therapeuticIndications: j['therapeuticIndications'] as String? ?? '',
      warnings: j['warnings'] as String? ?? '',
      adverseReactions: j['adverseReactions'] as String? ?? '',
      howToStore: j['howToStore'] as String? ?? '',
      pregnancyWarning: j['pregnancyWarning'] as String? ?? '',
      fiUrl: j['fiUrl'] as String? ?? '',
      rcmUrl: j['rcmUrl'] as String? ?? '',
    );
  }

  Medication toMedication() {
    PregnancyRiskCategory risco;
    try {
      risco = PregnancyRiskCategory.values.byName(riscoGravidezStr);
    } catch (_) {
      risco = PregnancyRiskCategory.B;
    }
    return Medication(
      id: id,
      cnp: cnp,
      nomeComercial: nomeComercial,
      formaFarmaceutica: formaFarmaceutica,
      substanciaAtiva: substanciaAtiva,
      dosagem: dosagem,
      riscoGravidez: risco,
      idadeMinima: idadeMinima,
      sujeitoReceitaMedica: sujeitoReceitaMedica,
      contraindicacoes: contraindicacoes,
      efeitosSecundariosComuns: efeitosSecundariosComuns,
      interacoesComSubstancias: const [],
    );
  }
}

/// Global singleton instance — initialize once in main.dart
final infarmedMedicationService = InfarmedMedicationService();
