import 'dart:convert';
import 'dart:io';

import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:sqlite3/sqlite3.dart';
import 'package:safemed/models/informative_bill.dart';
import 'package:safemed/models/medication.dart';

/// Service that loads medications from the bundled Infarmed SQLite database.
///
/// The database is generated by the webscraping pipeline and copied to
/// `assets/meds_infarmed.sqlite` so the Flutter app can read it at runtime.
class InfarmedMedicationService {
  static const _sqliteAssetPath = 'assets/meds_infarmed.sqlite';
  static const _jsonFallbackAssetPath = 'assets/medications_infarmed.json';

  final List<Medication> _medications = [];
  final List<InfarmedEntry> _entries = [];
  final List<InformativeBill> _informativeBills = [];
  bool _initialized = false;

  bool get isInitialized => _initialized;
  int get count => _medications.length;

  Future<void> init() async {
    if (_initialized) return;

    try {
      await _loadFromSqliteAsset();
    } catch (_) {
      try {
        await _loadFromJsonAsset();
      } catch (_) {
        _medications.clear();
        _entries.clear();
        _informativeBills.clear();
      }
    }

    _initialized = true;
  }

  List<Medication> get all => List.unmodifiable(_medications);

  List<Medication> search(String query) {
    final q = _normalize(query);
    if (q.isEmpty) return const [];
    return _medications.where((m) {
      return _normalize(m.nomeComercial).contains(q) ||
          _normalize(m.substanciaAtiva).contains(q);
    }).toList();
  }

  Medication? findByCnpem(String cnpem) {
    final clean = cnpem.replaceAll(RegExp(r'\D'), '');
    try {
      return _medications.firstWhere(
        (m) => m.cnp.replaceAll(RegExp(r'\D'), '') == clean,
      );
    } catch (_) {
      return null;
    }
  }

  Medication? findById(String id) {
    try {
      return _medications.firstWhere((m) => m.id == id);
    } catch (_) {
      return null;
    }
  }

  InfarmedEntry? getEntryById(String id) {
    try {
      return _entries.firstWhere((e) => e.id == id);
    } catch (_) {
      return null;
    }
  }

  InformativeBill? getInformativeBillById(String id) {
    try {
      return _informativeBills.firstWhere((bill) => bill.id.toString() == id);
    } catch (_) {
      return null;
    }
  }

  Future<void> _loadFromSqliteAsset() async {
    final dbFile = await _materializeAssetDatabase();
    final database = sqlite3.open(dbFile.path);

    try {
      final medRows = database.select(
        'SELECT * FROM medications ORDER BY dci, nome_medicamento',
      );
      final billRows = database.select('SELECT * FROM informative_bills');

      final billsByKey = <String, Map<String, Object?>>{};
      for (final row in billRows) {
        final sourceKey = _stringValue(row['source_key']);
        final dci = _stringValue(row['dci']);
        final medic = _stringValue(row['medicamento']);
        final key = _normalizeKey(
          sourceKey.isNotEmpty ? sourceKey : '$dci|$medic',
        );
        billsByKey[key] = row;
      }

      _medications.clear();
      _entries.clear();
      _informativeBills.clear();

      for (final row in medRows) {
        final dci = _stringValue(row['dci']);
        final medName = _stringValue(row['nome_medicamento']);
        final billRow = billsByKey[_normalizeKey('$dci|$medName')];

        final entry = InfarmedEntry.fromSqlite(row, billRow);
        _entries.add(entry);
        _medications.add(entry.toMedication());
        _informativeBills.add(entry.toInformativeBill());
      }
    } finally {
      database.dispose();
    }
  }

  Future<void> _loadFromJsonAsset() async {
    final jsonStr = await rootBundle.loadString(_jsonFallbackAssetPath);
    final list = jsonDecode(jsonStr) as List<dynamic>;
    _entries
      ..clear()
      ..addAll(
        list.map(
          (e) => InfarmedEntry.fromJson(e as Map<String, dynamic>),
        ),
      );
    _medications
      ..clear()
      ..addAll(_entries.map((entry) => entry.toMedication()));
    _informativeBills
      ..clear()
      ..addAll(_entries.map((entry) => entry.toInformativeBill()));
  }

  Future<File> _materializeAssetDatabase() async {
    final bytes = await rootBundle.load(_sqliteAssetPath);
    final directory = await getApplicationSupportDirectory();
    final file = File('${directory.path}${Platform.pathSeparator}meds_infarmed.sqlite');
    await file.writeAsBytes(
      bytes.buffer.asUint8List(bytes.offsetInBytes, bytes.lengthInBytes),
      flush: true,
    );
    return file;
  }

  static String _normalize(String input) {
    return input
        .toLowerCase()
        .replaceAll(RegExp(r'[àáâãä]'), 'a')
        .replaceAll(RegExp(r'[èéêë]'), 'e')
        .replaceAll(RegExp(r'[ìíîï]'), 'i')
        .replaceAll(RegExp(r'[òóôõö]'), 'o')
        .replaceAll(RegExp(r'[ùúûü]'), 'u')
        .replaceAll('ç', 'c')
        .replaceAll(RegExp(r'[^a-z0-9 ]'), ' ')
        .trim();
  }
}

class InfarmedEntry {
  final String id;
  final String cnp;
  final String nomeComercial;
  final String formaFarmaceutica;
  final String substanciaAtiva;
  final String dosagem;
  final String riscoGravidezStr;
  final int? idadeMinima;
  final bool sujeitoReceitaMedica;
  final List<String> contraindicacoes;
  final List<String> efeitosSecundariosComuns;
  final String titularAIM;
  final String aimStatus;
  final double? pricePVP;
  final String isGeneric;
  final String therapeuticIndications;
  final String warnings;
  final String adverseReactions;
  final String howToStore;
  final String pregnancyWarning;
  final String fiUrl;
  final String rcmUrl;
  final String pregnancyRiskText;
  final String breastfeedingRisk;
  final String breastfeedingNote;

  const InfarmedEntry({
    required this.id,
    required this.cnp,
    required this.nomeComercial,
    required this.formaFarmaceutica,
    required this.substanciaAtiva,
    required this.dosagem,
    required this.riscoGravidezStr,
    required this.idadeMinima,
    required this.sujeitoReceitaMedica,
    required this.contraindicacoes,
    required this.efeitosSecundariosComuns,
    required this.titularAIM,
    required this.aimStatus,
    required this.pricePVP,
    required this.isGeneric,
    required this.therapeuticIndications,
    required this.warnings,
    required this.adverseReactions,
    required this.howToStore,
    required this.pregnancyWarning,
    required this.fiUrl,
    required this.rcmUrl,
    required this.pregnancyRiskText,
    required this.breastfeedingRisk,
    required this.breastfeedingNote,
  });

  factory InfarmedEntry.fromJson(Map<String, dynamic> j) {
    return InfarmedEntry(
      id: j['id'] as String? ?? '',
      cnp: j['cnp'] as String? ?? '',
      nomeComercial: j['nomeComercial'] as String? ?? '',
      formaFarmaceutica: j['formaFarmaceutica'] as String? ?? '',
      substanciaAtiva: j['substanciaAtiva'] as String? ?? '',
      dosagem: j['dosagem'] as String? ?? '',
      riscoGravidezStr: j['riscoGravidez'] as String? ?? 'B',
      idadeMinima: _intValue(j['idadeMinima']),
      sujeitoReceitaMedica: j['sujeitoReceitaMedica'] as bool? ?? false,
      contraindicacoes: List<String>.from(j['contraindicacoes'] as List? ?? []),
      efeitosSecundariosComuns:
          List<String>.from(j['efeitosSecundariosComuns'] as List? ?? []),
      titularAIM: j['titularAIM'] as String? ?? '',
      aimStatus: j['aimStatus'] as String? ?? '',
      pricePVP: (j['pricePVP'] as num?)?.toDouble(),
      isGeneric: j['isGeneric'] as String? ?? '',
      therapeuticIndications: j['therapeuticIndications'] as String? ?? '',
      warnings: j['warnings'] as String? ?? '',
      adverseReactions: j['adverseReactions'] as String? ?? '',
      howToStore: j['howToStore'] as String? ?? '',
      pregnancyWarning: j['pregnancyWarning'] as String? ?? '',
      fiUrl: j['fiUrl'] as String? ?? '',
      rcmUrl: j['rcmUrl'] as String? ?? '',
      pregnancyRiskText: j['pregnancyRiskText'] as String? ?? '',
      breastfeedingRisk: j['breastfeedingRisk'] as String? ?? '',
      breastfeedingNote: j['breastfeedingNote'] as String? ?? '',
    );
  }

  factory InfarmedEntry.fromSqlite(
    Map<String, Object?> medicationRow,
    Map<String, Object?>? billRow,
  ) {
    final indicacoes = _listFromJson(billRow?['indicacoes_json']).cast<String>();
    final efeitosJson = _mapFromJson(billRow?['efeitos_json']);
    final frequentes = _listFromJson(efeitosJson['frequentes']);
    final outros = _listFromJson(efeitosJson['outros']);
    final adverse = <String>[...frequentes.cast<String>(), ...outros.cast<String>()];

    final pregnancyRiskText = _stringValue(billRow?['gravidez_seguro']);
    final pregnancyNote = _stringValue(billRow?['gravidez_nota']);
    final breastfeedingRisk = _stringValue(billRow?['amamentacao_seguro']);
    final breastfeedingNote = _stringValue(billRow?['amamentacao_nota']);

    return InfarmedEntry(
      id: _stringValue(medicationRow['n_registo']),
      cnp: _stringValue(medicationRow['cnpem']),
      nomeComercial: _stringValue(medicationRow['nome_medicamento']),
      formaFarmaceutica: _stringValue(medicationRow['forma_farmaceutica']),
      substanciaAtiva: _stringValue(medicationRow['dci']),
      dosagem: _stringValue(medicationRow['dosagem']),
      riscoGravidezStr: _resolvePregnancyCategory(
        pregnancyRiskText: pregnancyRiskText,
        pregnancyNote: pregnancyNote,
      ),
      idadeMinima: _intValue(billRow?['idade_minima']),
      sujeitoReceitaMedica: false,
      contraindicacoes: const [],
      efeitosSecundariosComuns: frequentes.cast<String>(),
      titularAIM: '',
      aimStatus: 'Autorizado',
      pricePVP: _doubleValue(medicationRow['price_pvp']),
      isGeneric: _stringValue(medicationRow['is_generic']) == '1'
          ? 'Sim'
          : 'Não',
      therapeuticIndications: indicacoes.join('; '),
      warnings: _stringValue(billRow?['aviso_critico']),
      adverseReactions: adverse.join('; '),
      howToStore: _stringValue(billRow?['conservacao']),
      pregnancyWarning: pregnancyNote.isNotEmpty
          ? pregnancyNote
          : _stringValue(billRow?['aviso_critico']),
        fiUrl: _stringValue(billRow?['pdf_url']).isNotEmpty
          ? _stringValue(billRow?['pdf_url'])
          : _stringValue(medicationRow['info_url']),
      rcmUrl: '',
      pregnancyRiskText: pregnancyRiskText,
      breastfeedingRisk: breastfeedingRisk,
      breastfeedingNote: breastfeedingNote,
    );
  }

  Medication toMedication() {
    PregnancyRiskCategory risco;
    try {
      risco = PregnancyRiskCategory.values.byName(riscoGravidezStr);
    } catch (_) {
      risco = PregnancyRiskCategory.B;
    }

    return Medication(
      id: id,
      cnp: cnp,
      nomeComercial: nomeComercial,
      formaFarmaceutica: formaFarmaceutica,
      substanciaAtiva: substanciaAtiva,
      dosagem: dosagem,
      riscoGravidez: risco,
      idadeMinima: idadeMinima,
      sujeitoReceitaMedica: sujeitoReceitaMedica,
      contraindicacoes: contraindicacoes,
      efeitosSecundariosComuns: efeitosSecundariosComuns,
      interacoesComSubstancias: const [],
    );
  }

  InformativeBill toInformativeBill() {
    return InformativeBill(
      id: _intValue(id) ?? 0,
      dci: substanciaAtiva,
      medName: nomeComercial,
      pdfUrl: fiUrl,
      therapeuticIndications: therapeuticIndications
          .split('; ')
          .where((item) => item.trim().isNotEmpty)
          .toList(),
      adverseReactions: [
        AdverseReactions(
          frequent: efeitosSecundariosComuns,
          other: adverseReactions
              .split('; ')
              .where((item) => item.trim().isNotEmpty)
              .toList(),
        ),
      ],
      howToStore: howToStore.isEmpty ? null : howToStore,
      criticalAdvices: warnings.isEmpty ? null : warnings,
      minimumAge: idadeMinima,
      pregnancyRisk: pregnancyRiskText.isEmpty ? null : pregnancyRiskText,
      pregnancyNote: pregnancyWarning.isEmpty ? null : pregnancyWarning,
      breastfeedingRisk: breastfeedingRisk.isEmpty ? null : breastfeedingRisk,
      breastfeedingNote: breastfeedingNote.isEmpty ? null : breastfeedingNote,
    );
  }
}

String _resolvePregnancyCategory({
  required String pregnancyRiskText,
  required String pregnancyNote,
}) {
  final normalized = pregnancyRiskText.trim().toLowerCase();
  if (normalized == 'sim') return 'B';
  if (normalized == 'condicionado') return 'C';
  if (normalized == 'nao') return 'X';

  final note = pregnancyNote.toLowerCase();
  if (note.contains('contraindicado')) return 'X';
  if (note.contains('usar a menor dose') || note.contains('risco')) return 'C';

  return 'B';
}

String _normalizeKey(String input) {
  return input.toLowerCase().replaceAll(RegExp(r'\s+'), ' ').trim();
}

String _stringValue(dynamic value) {
  if (value == null) return '';
  return value.toString().trim();
}

int? _intValue(dynamic value) {
  if (value == null) return null;
  if (value is int) return value;
  if (value is num) return value.toInt();
  final parsed = int.tryParse(value.toString().trim());
  return parsed;
}

double? _doubleValue(dynamic value) {
  if (value == null) return null;
  if (value is double) return value;
  if (value is int) return value.toDouble();
  final text = value.toString().replaceAll(',', '.');
  return double.tryParse(text);
}

Map<String, dynamic> _mapFromJson(dynamic value) {
  if (value == null) return const {};
  if (value is Map<String, dynamic>) return value;
  if (value is String && value.trim().isNotEmpty) {
    try {
      final decoded = jsonDecode(value);
      if (decoded is Map<String, dynamic>) return decoded;
    } catch (_) {
      return const {};
    }
  }
  return const {};
}

List<dynamic> _listFromJson(dynamic value) {
  if (value == null) return const [];
  if (value is List<dynamic>) return value;
  if (value is String && value.trim().isNotEmpty) {
    try {
      final decoded = jsonDecode(value);
      if (decoded is List<dynamic>) return decoded;
    } catch (_) {
      return const [];
    }
  }
  return const [];
}

/// Global singleton instance — initialize once in main.dart.
final infarmedMedicationService = InfarmedMedicationService();
